- server/manifest.go
- webapp/src/manifest.js
Sigh, I forgot to generate the code after updating `plugin.json`. Fixed.
> generate code after bumping versions

- Makefile
- build/setup.mk
The old commands throws
```bash
/bin/sh: 1: [[: not found
You must clone github.com/mattermost/mattermost-utilities repo in .. to use this command
/bin/sh: 1: [[: not found
Makefile:159: recipe for target 'i18n-extract' failed
make: *** [i18n-extract] Error 127
```
on my ubuntu.
I fixed this and refactored the target a bit to make it Independent of the current working directory.
Site note: I would like to update the `Makefile` of the sample plugin with this command. Any objections?
> Fix i18n-extract

- server/message_hooks.go
Previously when the bot posted a message an infinity loop would occur, because in `MessageHasBeenPosted` a new message would be created.
This PR fixed this by ignoring posts from the bot account in `MessageHasBeenPosted`.
> Fix infinity loop of message posting

- server/message_hooks.go
I would like (2/5) to get rid of the demo user account, but this out of scope for this PR.
Fixes https://mattermost.atlassian.net/browse/MM-16305
> [MM-16305] Allow posts from demo bot account in demo channel

- README.md
The `mattermost-plugin-sample` repo is being renamed to `mattermost-plugin-starter-template`. As a result, any references to the original name in documentation needs to be updated, including this repo.
https://mattermost.atlassian.net/browse/MM-14189
> Update README references to "mattermost-plugin-sample" to be "mattermost-plugin-starter-template"

- server/README.md
- server/command_hooks.go
- webapp/src/components/ephemeral_post_type.jsx
- webapp/src/plugin.jsx
adds an `/ephemeral_override` command to demonstrate overriding an ephemeral post with the webapp using a `type` prop.
https://github.com/mattermost/mattermost-server/issues/10797
> added ephemeral_override command

- README.md
Updated main Readme to reference the Mattermost version of the plugin.json file to avoid reference to old versions.
> Update MM Version on README.md

- server/command_hooks.go
- server/http_hooks.go
Not mention in the ticket but it might be helpful to extend `/dialog` command to have relative callback URL when trying interactive dialog.
Note that this demo plugin may be used for end-to-end testing in the future.
Relative URL as seen in request payload:
Command response once submitted:
> MM-10982 Extend "/dialog" command to generate interactive dialog with relative callback URL

- go.mod
- go.sum
- plugin.json
- server/message_hooks.go
Tweak the `MessageWillBePosted` hook to dismiss posts that try to
at-mention the `@demo_plugin` user.
When enabled, the plugin already disallows posts in the demo plugin channel, but does so by displaying an error and causing the post to enter a retry/cancel state. It used to do that for at-mentions in any channel, but is now changed as per above.
This leverages the functionality provided by a community member in https://mattermost.atlassian.net/browse/MM-15694.
> MM-15694: Illustrate plugin.DismissPostError

- webapp/i18n/en.json
- webapp/src/plugin.jsx
Illustrate how to invoke an interactive dialog without a trigger id, e.g. from a main menu option vs. a typical slash command interaction.
See https://mattermost.atlassian.net/browse/MM-15340
> MM-15340: dialog without trigger id

- server/configuration.go
- server/configuration_test.go
Plugins weren't able to successfully attach a file to a post in 5.12 because a unintentional security change. Verify that this is now working by attaching the demo plugin's configuration as a `.json` attachment to the `OnConfigChange: loading new configuration` posts it makes in the demo plugin channel.
> MM-17438: attach file to post

- plugin.json
- webapp/src/plugin.jsx
- Adds support for new `hideRHSPlugin `from `registerRightHandSidebarComponent `to close the right-hand sidebar
Fixes https://github.com/mattermost/mattermost-server/issues/11893
JIRA: https://mattermost.atlassian.net/browse/MM-17810
> Added hideRHSPlugin action support to the plugin

- webapp/src/plugin.jsx
There are issues rendering nested post menu submenus in the RHS. For now, restrict to just a single level instead of arbitrary nesting.
Relates-to: https://mattermost.atlassian.net/browse/MM-20749
Relates-to: https://github.com/mattermost/mattermost-webapp/pull/4372
> MM-20749: restrict post menu nesting

- webapp/package-lock.json
This addresses security fixes with an `npm audit fix --save`.
See also https://github.com/mattermost/mattermost-plugin-starter-template/pull/75.
> npm audit fix --save

- server/activate_hooks.go
- server/activate_hooks_test.go
Instead of hard-failing the demo plugin, just log an error when
showcasing the "required configuration" portion of the plugin. Right
now, the error message doesn't specifically call out next steps for
someone using the plugin, making it hard to use as a feature.
Fixes: https://mattermost.atlassian.net/browse/MM-22414
> MM-22414: relax required server configuration

- .circleci/config.yml
Build the plugin every day to spot broken builds earlier. I'm 0/5 on weekly/daily. Thoughts?
https://community.mattermost.com/core/pl/pxb4cdusbtytxdgyd3zde5fd9a
> Add nightly builds

- webapp/README.md
- webapp/src/components/right_hand_sidebar/index.js
- webapp/src/components/right_hand_sidebar/rhs_view.jsx
- webapp/src/plugin.jsx
Adding example of route registration added in: https://github.com/mattermost/mattermost-webapp/pull/5367
Routes can be found at:
- `/plug/com.mattermost.demo-plugin/roottest`
- `/<teamname>/com.mattermost.demo-plugin/teamtest`
https://mattermost.atlassian.net/browse/MM-24503
> MM-24503 Adding custom route example.

- .golangci.yml
- Makefile
- build/deploy/main.go
- server/activate_hooks.go
- server/activate_hooks_test.go
- server/command_hooks.go
- server/configuration.go
- server/configuration_test.go
- server/file_hooks.go
- server/http_hooks.go
- server/http_hooks_test.go
- server/job.go
- server/login_hooks.go
- server/message_hooks.go
- server/plugin.go
- server/plugin_message.go
- server/user_hooks.go
Downstream the `golangci-lint` config from https://github.com/mattermost/mattermost-plugin-starter-template/pull/90 and sync `build`.
Most changes are straightforward and just style wise. I did comment on the more tricky ones.
Follow up on https://github.com/mattermost/mattermost-plugin-autolink/pull/108
> Integrate GolangCI-Lint

- plugin.json
- server/manifest.go
- webapp/src/manifest.js
Cut a new release for `5.26` RC testing. Not much to review: https://github.com/mattermost/mattermost-plugin-demo/compare/16c47d26aaa33eeedd199237d6a679608dfb4977...master. https://github.com/mattermost/mattermost-plugin-demo/pull/105 is the only meaningful change.
> Bump version to v0.8.0

- webapp/src/components/link_tooltip/link_tooltip.jsx
This PR adjusts the ToolTip theme to match the user-specified theme.  I kept the styling the same except for 
* border: `1px solid ${hexToRGB(theme.centerChannelColor, '0.16')}`
* color: `theme.centerChannelColor`
* backgroundColor: `theme.centerChannelBg`
I also tool the border and hexToRGB function from the github plugin.
before 
after 
before 
after 
https://mattermost.atlassian.net/browse/MM-31344
> [MM-31344] Adjust tooltip to match user theme

- webapp/webpack.config.js
For some more context, see [here](https://community.mattermost.com/core/pl/1fkkx7pj1jrwffrc6drh3x71eh). The short version though is that we updated the web app to React 17, and there's a chance that plugins will have some issues with it because they're compiled with the React 16 version of ReactDOM. I'm submitting PRs to the 3 products, the demo plugin, and the plugin template to have them use the web app's version of React DOM to fix any immediate issues, but we'll want to properly migrate them to React 17 going forward.
https://mattermost.atlassian.net/browse/MM-47046
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1489
https://github.com/mattermost/focalboard/pull/3861
https://github.com/mattermost/mattermost-plugin-todo/pull/190 …
> MM-47046 Use version of React DOM provided by web app

- server/login_hooks.go
- server/user_hooks.go
For https://github.com/mattermost/mattermost/pull/20894
> Add example use of UserHasBeenDeactivated hook

- server/http_hooks.go
I added the feature that checks the Authorization header.
I implemented this feature to test [this PR](https://github.com/mattermost/mattermost/pull/24391)
> Add the feature to check the authorization header

- server/configuration.go
When the demo plugin's config is first saved, the `ConfigurationWillBeSaved` hook is called. In this first call, there is no config saved for the demo plugin at config.json's `PluginSettings.Plugins`. This causes a nil pointer in this hook as the plugin assumes it's defined.
This PR makes it so we return successfully in the case that this is the first config save for the plugin's installation.
Fixes https://mattermost.atlassian.net/browse/MM-57423
> Fix nil pointer in ConfigurationWillBeSaved

- webapp/src/plugin.jsx
This PR fix the issue that interactive dialog opened from main menu doesn't work fine.
[screen.webm](https://github.com/mattermost/mattermost-plugin-demo/assets/1453749/9639bc2c-6e68-4958-95fa-7a476cfdeb2b)
N/A
> Fix invalid parameter for openInteractiveDialog
