mattermost/mattermost-plugin-demo

webapp/src/components/icons.jsx

This would better be handled by https://mattermost.atlassian.net/browse/MM-11386.

tweak channel header icon

---

Makefile
build/manifest/go.mod
build/manifest/go.sum
server/go.mod
server/go.sum
webapp/package-lock.json
webapp/src/actions.js
webapp/src/components/icons.jsx
webapp/src/plugin.jsx

- Also fixed Makefile and vgo files just enough to get it to compile for someone who already has vgo installed. 
Webapp PR:  https://github.com/mattermost/mattermost-webapp/pull/1488

MM-10657 Adding file upload button to demo plugin.

---

server/Gopkg.lock
server/Gopkg.toml
server/activate_hooks.go
server/activate_hooks_test.go

This PR adds a demo usage of `GetServerVersion()' and add unit tests for this. It also changes some code to use Idiomatic error handling.
See https://github.com/mattermost/mattermost-server/pull/9429

Add demo usage of GetServerVersion 

---

server/activate_hooks_test.go
server/http_hooks_test.go

This PR adds tests for `OnDeactivate` and `ServeHTTP`.

Add tests for ServeHTTP and OnDeactivate

---

.travis.yml
Makefile

Downstream from https://github.com/mattermost/mattermost-plugin-sample/pull/15

Add check-style makefile target

---

CHANGELOG.md
plugin.json

Planning on cutting a new version for testing.

bump version to 0.0.5

---

server/README.md
server/file_hooks.go
server/user_hooks.go

Fix for https://github.com/mattermost/mattermost-server/issues/10408

Add hooks for UserHasBeenCreated, FileWillBeUploaded

---

Makefile
webapp/i18n/en.json
webapp/i18n/es.json
webapp/package-lock.json
webapp/package.json
webapp/src/components/left_sidebar_header/left_sidebar_header.jsx
webapp/src/components/link_tooltip/link_tooltip.jsx
webapp/src/components/root/root.jsx
webapp/src/components/user_actions/user_actions.jsx
webapp/src/plugin.jsx
webapp/webpack.config.js

Implementation of: https://github.com/mattermost/mattermost-webapp/pull/2621

MM-14860 Adding localization.

---

.circleci/config.yml
server/activate_hooks.go
server/command_hooks.go

Fixes https://github.com/mattermost/mattermost-server/issues/10901
* adds /crash command that crashes the plugin by divide by zero error

Mm 15584 - add /crash command that crashes the plugin

---

plugin.json
server/activate_hooks.go

See #34 for a discussion about this

Require Mattermost Server v5.12

---

webapp/README.md

Fixes the link to components folder in webapp/README.md

Fix link to components folder in README

---

server/command_hooks.go

Illustrate a boolean selector in an interactive dialog:

MM-14273: demo boolean selector

---

server/command_hooks.go

Jira - https://mattermost.atlassian.net/browse/MM-14593
Added while testing interactive dialog
Note: Min. version is 5.16.0 which is already set at https://github.com/mattermost/mattermost-plugin-demo/blob/master/plugin.json#L6

Add password input for interactive dialog

---

plugin.json
server/manifest.go
webapp/package.json
webapp/src/manifest.js

This should be used for 5.16 release testing. Please review quickly and just merge when all reviews are done.
One outstanding question is, if https://github.com/mattermost/mattermost-plugin-demo/pull/68 should go into this.

Release v0.3.0

---

README.md

Follow up on https://community.mattermost.com/private-core/pl/uj7pxbywb38opc3smpj9gq8kxc

Add section about releasing this plugin

---

plugin.json
server/manifest.go
webapp/src/manifest.js

This release should be used for the MM 5.18 release testing.

Release v0.4.0

---

server/command_hooks.go

Add select element with default to `/dialog`. This helps testing https://mattermost.atlassian.net/browse/MM-15917.
https://mattermost.atlassian.net/browse/MM-15917

Add select element with default value to dialog

---

plugin.json
server/configuration.go
server/message_hooks.go

I tried to come up with a creative example usage but ended up just copying the code from `RandomSecret`. I'm open for ideas.
Follow up on https://github.com/mattermost/mattermost-server/pull/13800

Add example usage of number type

---

plugin.json
server/manifest.go
webapp/src/manifest.js

I missed the 5.20 release testing, which is unfortunate. Despite this I think it's valuable to cut a release every two month.

Release v0.5.0

---

go.mod
plugin.json
server/README.md
server/command_hooks.go

- Demonstrate usage of the `GetWithOptions` method to get FileInfos that was added in https://github.com/mattermost/mattermost-server/pull/13647/ 
- Part of https://github.com/mattermost/mattermost-server/issues/12699 and
https://mattermost.atlassian.net/browse/MM-17912

MM-17912 - slash command to exercise FileInfo search API

---

.circleci/config.yml

See JIRA ticket
Part of https://mattermost.atlassian.net/browse/MM-23138

Drop deploy-release job

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Cut a new release for `5.22` RC testing.

Release v0.6.0 

---

go.mod
go.sum
server/command_hooks.go
server/http_hooks.go

This PR will showcase using of the icons in slash command autocomplete.
Fixes https://mattermost.atlassian.net/browse/MM-24767

[MM-24767] autocomplete icons

---

README.md

PR to add release version and Help Wanted Badges to the readme
n/a

add badges for latest release and HW

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Cut a new release for `5.22` RC testing.

Release v0.7.0

---

build/manifest/main.go

Required for https://github.com/mattermost/circleci-orbs/pull/20

Fix linter issue for golanci-lint v1.13.0

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Cut a new release to be used in E2E testing
https://community.mattermost.com/core/pl/9rbacrfxeibxud35r3keh3k5me

Release v0.9.0

---

server/file_hooks.go

Signed-off-by: Adithya Krishna <aadithya794@gmail.com>
Updates FileWillBeUploaded function signature to be similar to what's defined in the interface
This PR Fixes #125

Matched FileWillBeUploaded Signature to Defined in Interface

---

.golangci.yml
go.mod
go.sum
server/configuration.go

Fix linter errors caused by `golangci-lint` update
None

Fix linter errors
